build:
    cargo build --target wasm32-unknown-unknown --release
    mkdir -p wasm
    wasm-opt -Oz -o askalono_wasm_optimized.wasm target/wasm32-unknown-unknown/release/askalono_wasm.wasm
    wasm-bindgen askalono_wasm_optimized.wasm --out-dir wasm

serve:
    npm run serve

package: build
    rm -rf dist
    webpack
    cp index.html dist