build:
    cargo +nightly build --target wasm32-unknown-unknown --release
    mkdir -p build/web build/node web node
    wasm-opt -Oz -o ./build/askalono.wasm-tmp ./target/wasm32-unknown-unknown/release/askalono_wasm.wasm

    wasm-bindgen ./build/askalono.wasm-tmp --out-dir ./build/web --browser
    cp build/web/*.js build/web/*.ts build/web/*.wasm web
    wasm-bindgen ./build/askalono.wasm-tmp --out-dir ./build/node --nodejs
    cp build/node/*.js build/node/*.ts build/node/*.wasm node
